SELECT 
        OT.OPTION_TYPE_ID,
        OT.OPTION_TYPE_NAME,
        OCG.OPTION_CG_ID,
        OCG.OPTION_CG_NAME,
        OV.OPTION_ID,
        OV.OPTION_VALUE
FROM OPTION_TYPE OT
JOIN OPTION_CG OCG ON OT.OPTION_TYPE_ID = OCG.OPTION_TYPE_ID
JOIN OPTION_VALUE OV ON OT.OPTION_TYPE_ID = OV.OPTION_TYPE_ID AND OCG.OPTION_CG_ID = OV.OPTION_CG_ID;

SELECT
    OPTION_TYPE_ID,
    OPTION_TYPE_NAME
FROM
    OPTION_TYPE;

SELECT
    IT.ITEM_NO,
    IT.CG_CODE,
    IT.ITEM_NAME,
    IT.ITEM_PRICE,
    IT.ITEM_DISCOUNT,
    IT.ITEM_MANUFACTURE,
    IT.ITEM_CONTENT,
    IT.ITEM_UP_FOLDER,
    IT.ITEM_IMG,
    IT.ITEM_AMOUNT,
    IT.ITEM_BUY,
    IT.ITEM_SHORT_DETAIL,
    IT.ITEM_DATE,
    IT.ITEM_UPDATEDATE,
    IO.OPTION_TYPE_ID,
    OT.OPTION_TYPE_NAME,
    IO.OPTION_CG_ID,
    OCG.OPTION_CG_NAME,
    IO.OPTION_ID,
    OV.OPTION_VALUE
FROM
    ITEM_TBL IT
JOIN
    ITEM_OPTION IO ON IT.ITEM_NO = IO.ITEM_NO
LEFT JOIN
    OPTION_TYPE OT ON IO.OPTION_TYPE_ID = OT.OPTION_TYPE_ID
LEFT JOIN
    OPTION_CG OCG ON IO.OPTION_CG_ID = OCG.OPTION_CG_ID
LEFT JOIN
    OPTION_VALUE OV ON IO.OPTION_ID = OV.OPTION_ID;
    
    
    SELECT
			OCG.OPTION_CG_ID,
	        OCG.OPTION_CG_NAME,
	        OV.OPTION_ID,
	        OV.OPTION_VALUE
	FROM
		OPTION_CG OCG
			JOIN 
				OPTION_VALUE OV
			ON
				OCG.OPTION_CG_ID = OV.OPTION_CG_ID
	WHERE
		OCG.OPTION_CG_ID = 2;