
-- 포트폴리오 쇼핑몰 작업.

-- 회원정보 테이블

CREATE TABLE MEMBER_TAB 
(
        MEMBER_ID             VARCHAR2(15)            NOT NULL,
        MEMBER_NAME           VARCHAR2(30)            NOT NULL,       -- 이름
        MEMBER_EMAIL          VARCHAR2(50)            NOT NULL,       -- 이메일
        MEMBER_PASSWORD       CHAR(60)                NOT NULL,       -- 비밀번호 암호화 처리.
        MEMBER_ZIPCODE        CHAR(5)                 NOT NULL,       -- 우편번호
        MEMBER_ADDR           VARCHAR2(100)           NOT NULL,       -- 주소
        MEMBER_DEADDR         VARCHAR2(100)           NOT NULL,       -- 상세주소
        MEMBER_PHONE          VARCHAR2(15)            NOT NULL,       -- 연락처    
        MEMBER_POINT          NUMBER DEFAULT 0        NOT NULL,       -- 포인트
        MEMBER_LASTLOGIN      DATE DEFAULT SYSDATE    NOT NULL,       -- 최근 접속일
        MEMBER_DATESUB        DATE DEFAULT SYSDATE    NOT NULL,       -- 등록일
        MEMBER_UPDATEDATE     DATE DEFAULT SYSDATE    NOT NULL        -- 정보 수정일 
);
DROP TABLE MEMBER_TAB;
SELECT * FROM MEMBER_TAB;

-- 게시판 테이블

CREATE TABLE BOARD (
		  
	    BNO    NUMBER,                                  -- 글번호
	    TITLE       VARCHAR2(100)   NOT NULL,           -- 제목
	    CONTENT     VARCHAR2(1000)  NOT NULL,           -- 내용
	    AUTHOR      VARCHAR2(100)   NOT NULL,           -- 작성자
	    CREATEDATE  DATE            DEFAULT SYSDATE,    -- 등록일
	    MODIFYDATE  DATE            DEFAULT SYSDATE,    -- 수정일
	    READCOUNT   NUMBER          DEFAULT 0,
	    CONSTRAINT  PK_BOARD       PRIMARY KEY(BNO)
		);
DROP TABLE BOARD;
-- 시퀀스 생성 (게시글 번호)
CREATE SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD;

SELECT * FROM BOARD;
COMMIT;

SELECT * FROM BOARD;

-- 관리자 페이지 전용 관리자 계정 테이블.

CREATE TABLE ADMINISTRATOR_TBL (
    ADMINISTRATOR_ID            VARCHAR2(15)    PRIMARY KEY,
    ADMINISTRATOR_PW            CHAR(60)        NOT NULL,
    ADMINISTRATOR_LOGIN_TIME    DATE
);   

-- 관리자 아이디 비밀번호 admin , 1234
INSERT INTO ADMINISTRATOR_TBL VALUES('admin', '$2a$10$dQFCMr0udCI865eG6SoIcOaNr3Y/dgBX.R4qf6rX5KA3jciSnnNjG',SYSDATE);
DROP TABLE ITEM_COMP_TBL;
CREATE TABLE ITEM_COMP_TBL
(
    GRADE           NUMBER          PRIMARY KEY,
    GEN             VARCHAR2(20)    UNIQUE,
    RAM_TYPE        VARCHAR2(10)    UNIQUE,
    M2              CHAR            UNIQUE,
    F_FACTOR        VARCHAR2(10)    UNIQUE,
    GENERAL_TYPE    VARCHAR2(20)    UNIQUE
);

INSERT INTO ITEM_COMP_TBL (GRADE)
    VALUES('1');
INSERT INTO ITEM_COMP_TBL (GRADE)
    VALUES('2');    
INSERT INTO ITEM_COMP_TBL (GRADE)
    VALUES('3');
INSERT INTO ITEM_COMP_TBL (GRADE)
    VALUES('4');
    
INSERT INTO ITEM_COMP_TBL (GEN)
    VALUES('Intel 11');
INSERT INTO ITEM_COMP_TBL (GEN)
    VALUES('Intel 12');
INSERT INTO ITEM_COMP_TBL (GEN)
    VALUES('Intel 13');
INSERT INTO ITEM_COMP_TBL (GEN)
    VALUES('Intel 14');
INSERT INTO ITEM_COMP_TBL (GEN)
    VALUES('AMD AM4');
INSERT INTO ITEM_COMP_TBL (GEN)
    VALUES('AMD AM5');
    


    
    
DROP TABLE CG_CODE_TBL;
CREATE TABLE CG_CODE_TBL
(
    CG_CODE     NUMBER  PRIMARY KEY,
    CG_PRTCODE  NUMBER  NULL,
    CG_NAME     VARCHAR2(40)  NOT NULL,
    FOREIGN KEY(CG_PRTCODE) REFERENCES CG_CODE_TBL(CG_CODE)
);

INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (1,NULL,'CPU');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (2,NULL,'쿨러');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (3,NULL,'메인보드(Mainboard)');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (4,NULL,'램(Memory)');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (5,NULL,'그래픽카드(VGA)');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (6,NULL,'저장장치(HDD,SSD)');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (7,NULL,'파워');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (8,NULL,'케이스');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (9,NULL,'기타');

INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (11,1,'인텔(Intel)');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (12,1,'AMD');
    
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (21,2,'공랭');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (22,2,'수냉');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (23,2,'케이스,시스템 팬');
    
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (31,3,'인텔 시스템용');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (32,3,'AMD 시스템용');

INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (41,4,'DDR4');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (42,4,'DDR5');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (43,4,'노트북용 DDR4');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (44,4,'노트북용 DDR5');

INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (51,5,'엔비디아(GEFORCE)');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (52,5,'AMD(RADEON)');
    
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (61,6,'하드디스크(HDD)');    
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (62,6,'SSD');    
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (63,6,'SSD(M.2)');   

INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (71,7,'600W 이하');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (72,7,'600W 이상');

INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (81,8,'중형 케이스(미들타워 M-ATX)');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (82,8,'대형 케이스(빅타워 ATX)');

INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (91,9,'모니터');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (92,9,'마우스');
INSERT INTO CG_CODE_TBL (CG_CODE,CG_PRTCODE,CG_NAME) 
    VALUES (93,9,'키보드');

COMMIT;

DROP TABLE ITEM_TBL;
CREATE TABLE ITEM_TBL (
        ITEM_NO             NUMBER                  NOT NULL,
        CG_CODE             NUMBER                  NOT NULL,
        ITEM_NAME           VARCHAR2(50)            NOT NULL,
        ITEM_PRICE          NUMBER                  NOT NULL,
        ITEM_DISCOUNT       NUMBER                  NULL,
        ITEM_MANUFACTURE    VARCHAR2(50)            NOT NULL,
        ITEM_CONTENT        VARCHAR2(4000)          NOT NULL,       -- 내용이 4000BYTE 초과여부판단? CLOB
        ITEM_UP_FOLDER      VARCHAR2(50)            NOT NULL,
        ITEM_IMG            VARCHAR2(100)           NOT NULL,       -- 날짜폴더경로가 포함하여 파일이름저장
        ITEM_AMOUNT         NUMBER                  NOT NULL,
        ITEM_BUY            CHAR(1)                 NOT NULL,       -- 대문자 Y또는 N값.
        ITEM_SHORT_DETAIL   VARCHAR2(2000)          NULL,
        ITEM_DATE           DATE DEFAULT SYSDATE    NULL,
        ITEM_UPDATEDATE     DATE DEFAULT SYSDATE    NULL,
        GRADE               NUMBER                  NULL,
        GEN                 VARCHAR2(20)            NULL,
        RAM_TYPE            VARCHAR2(10)            NULL,
        M2                  CHAR(1)                 NULL,
        F_FACTOR            VARCHAR2(10)            NULL,
        
        CONSTRAINT  PK_ITEM_NO      PRIMARY KEY(ITEM_NO),
        FOREIGN KEY(CG_CODE)        REFERENCES CG_CODE_TBL(CG_CODE)
);
CREATE SEQUENCE SEQ_ITEM_TBL;
INSERT INTO ITEM_TBL 
(GRADE)
VALUES ('1');
item_no, cg_code, item_name, item_price, item_discount, item_manufacture, item_content, item_up_folder, item_img, item_amount, item_buy, item_short_detail, item_date, item_updatedate, grade, gen, ram_type, m2, f_factor







